### ISSUE TITLE
xdebug on Docker for Mac

### ISSUE THREAD

**Issue by jansenfelipe** [codecasts/ambientum#103]
Hello! I'm using Docker on a Macbook and xdebug did not work.

Searching on some forums, I discovered that the `xdebug.remote_host` setting should point to the address `docker.for.mac.localhost`.

I noticed that the `docker.for.mac.localhost` domain resolves a **different ip** than the output `/sbin/ip route|awk '/default/ { print $3 }'` https://github.com/codecasts/ambientum/blob/master/php/7.1/start.sh#L33

Would it be the case to add a validation in the `start.sh` file to check if it is a Docker running on OSX?

Something like:
```ssh
if ping -c 1 docker.for.mac.localhost > /dev/null; then sed -i "s/`/sbin/ip route|awk '/default/ { print $3 }'`/docker.for.mac.localhost/g" /etc/php7/conf.d/00_xdebug.ini; fi;
```

**Comment by cichondev** [comment]
Hi @jansenfelipe, some news over your issue? I created the issue #104 recently, but imagine which the cases can be relationated.

**Comment by jansenfelipe** [comment]
Hi @cichondev !

I created a new file `start.sh` in my project:

```sh
#!/bin/bash

echo "xdebug.remote_autostart=1" | sudo tee -a /etc/php7/conf.d/00_xdebug.ini > /dev/null

if sudo ping -c 1 docker.for.mac.localhost > /dev/null; then sudo sed -i "s/`/sbin/ip route|awk '/default/ { print $3 }'`/docker.for.mac.localhost/g" /etc/php7/conf.d/00_xdebug.ini; fi;

/home/ambientum/start.sh
```

Later, I change `docker-compose.yml` add `command` param:

```yaml
services:

  web:
    image: ambientum/php:7.1-nginx
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    environment:
      - XDEBUG_ENABLED=true
    command: /var/www/app/start.sh
```

This worked for me. 😄
