### ISSUE TITLE
Add MongoDb

### ISSUE THREAD

**Issue by DiegoJG** [codecasts/ambientum#50]
It would be great if you could add MongoDb to this project.
Thank you!

**Comment by hernandev** [comment]
you mean the php extension or a mongo db image?

**Comment by DiegoJG** [comment]
An image of mongo DB, I do not have much experience with docker-compose, but I'm trying to "implement".

**Comment by hernandev** [comment]
Ok, the mongoDB image you're looking for is this one:

https://hub.docker.com/_/mongo/

**Comment by hernandev** [comment]
One example of using it inside `docker-compose.yml`
```    
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
```
