### ISSUE TITLE
vuejs support

### ISSUE THREAD

**Issue by mits87** [codecasts/ambientum#62]
Hi,

when I try use your example "Vue.js docker-compose.yml" and run: `docker-compose up` then I get errors: 

> vue-dev  |
> vue-dev  | > @ watch /var/www/app
> vue-dev  | > cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> vue-dev  |
> vue-dev  |  10% building modules 2/2 modules 0 active
> vue-dev  | Webpack is watching the files…
> vue-dev  |
>  95% emitting ERROR  Failed to compile with 2 errors09:40:02
> vue-dev  |
> vue-dev  |  error  in ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  | Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux-x64-57/binding.node
> vue-dev  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | Found bindings for the following environments:
> vue-dev  |   - OS X 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | This usually happens because your environment has changed since running `npm install`.
> vue-dev  | Run `npm rebuild node-sass --force` to build the binding for your current environment.
> vue-dev  |
> vue-dev  |  @ ./resources/assets/sass/app.scss 4:14-266
> vue-dev  |  @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  |  error  in ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  | Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux-x64-57/binding.node
> vue-dev  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | Found bindings for the following environments:
> vue-dev  |   - OS X 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | This usually happens because your environment has changed since running `npm install`.
> vue-dev  | Run `npm rebuild node-sass --force` to build the binding for your current environment.

Could you fix it?

**Comment by vs0uz4** [comment]
I also got problems with `node-sass` in version 8 of nodejs. I decided to switch to the nodejs version for 7.

Change your 'docker-composer.yaml' line to the image below.
```
image: ambientum/node:7
```
It worked for me.

**Comment by mits87** [comment]
Thank you for your reply. I changed to node:7 but I have the same error: 

> vue-dev  | Webpack is watching the files…
> vue-dev  |
>  95% emitting ERROR  Failed to compile with 2 errors12:44:23 PM
> vue-dev  |
> vue-dev  |  error  in ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  | Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux-x64-51/binding.node
> vue-dev  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
> vue-dev  |
> vue-dev  | Found bindings for the following environments:
> vue-dev  |   - OS X 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | This usually happens because your environment has changed since running `npm install`.
> vue-dev  | Run `npm rebuild node-sass --force` to build the binding for your current environment.
> vue-dev  |
> vue-dev  |  @ ./resources/assets/sass/app.scss 4:14-266
> vue-dev  |  @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  |  error  in ./resources/assets/sass/app.scss
> vue-dev  |
> vue-dev  | Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux-x64-51/binding.node
> vue-dev  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
> vue-dev  |
> vue-dev  | Found bindings for the following environments:
> vue-dev  |   - OS X 64-bit with Node.js 8.x
> vue-dev  |
> vue-dev  | This usually happens because your environment has changed since running `npm install`.
> vue-dev  | Run `npm rebuild node-sass --force` to build the binding for your current environment.

:(

**Comment by mits87** [comment]
Thank you for your response. 
Yes, my system i OSX and I know these solutions but it works only for local machine (if I run `npm run watch` on local environment). 
When I run docker: `Vue.js docker-compose.yml` then problem is the same. IMHO the solution should be implemented in docker container. 
What are you thinking about it?

**Comment by vs0uz4** [comment]
How is your docker-compose.yml?

**Comment by mits87** [comment]
my docker-compose.yml is the same as example of your package:

> version: '3'
> services:
>   dev:
>     image: ambientum/node:7
>     container_name: vue-dev
>     command: npm run watch
>     volumes:
>       - .:/var/www/app
>     ports:
>       - 8080:8080

**Comment by vs0uz4** [comment]
Try this settings

```
version: '2'

volumes:
  vue-dev-config:
    driver: local
  vue-dev-cache:
    driver: local
  vue-dev-local:
    driver: local
  vue-dev-yarn:
    driver: local
  vue-dev-npm:
    driver: local

services:
  dev:
    image: ambientum/node:7
    container_name: vue-dev
    command: npm run watch
    volumes:
      - .:/var/www/app
      - vue-dev-config:/home/ambientum/.config
      - vue-dev-cache:/home/ambientum/.cache
      - vue-dev-local:/home/ambientum/.local
      - vue-dev-yarn:/home/ambientum/.yarn
      - vue-dev-npm:/home/ambientum/.npm
    ports:
      - 8080:8080
```
In this way, the previously proposed solutions will persist in the configured volumes.
