### ISSUE TITLE
Supervisord

### ISSUE THREAD

**Issue by mits87** [codecasts/ambientum#66]
Hi, 

I would like to ask you any plans to create `supervisord` service for docker-compose?

For instance most of Laravel applications use queues (many queues with different name) by supervisord. 

So if I would like control all queues I create supervisord conf and I dispatch: 
`supervisord -c config/supervisord/supervisor.conf` after that all of my queues are running. 
This solution is easier than this:

```yml
  queue_status_process_node_requests:
    image: ambientum/php:latest
    container_name: app_status_process_node_requests
    command: php artisan queue:work redis --queue=status_process_node_requests
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - redis

  queue_stop_process_node_requests:
    image: ambientum/php:latest
    container_name: app_stop_process_node_requests
    command: php artisan queue:work redis --queue=stop_process_node_requests
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - redis

...
```

easier will be something like this:

```yml
  queues:
    image: ambientum/supervisord:latest
    container_name: app-supervisord
    command: supervisord -c config/supervisord/supervisor.conf
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - redis
```

What do you think about this?

**Comment by hernandev** [comment]
@mits87 No, no plans and that's why:

Docker containers are only alive while the main (pid 1) process is still running.

When a given process fails, the container itself dies.

So, Docker has a special instruction: `restart`

With restart you can define the policy of what to do when a container dies.

Possible values:

`no` -> default, the container will not start automatically.
`on-failure` -> only when the container exists with a error.
`always` -> the container will restart automatically, even after a `docker stop` or `docker-compose down`
`unless-stopped` -> if you stop the container, it will not start back, otherwise, it will start.

So, no need for supervisord or pm2. Docker itself can handle auto restarts on failures.

To use that within a docker-compose.yml file, just add the restart: entry on the service you want to keep running:

```
  # QUEUE
  queue:
    image: ambientum/php:7.1
    container_name: myapp-queue
    command: php artisan horizon
    restart: unless-stopped
```

Thanks!
