### ISSUE TITLE
Erro ao utilizar portas diferentes para o Mysql

### ISSUE THREAD

**Issue by julihermes** [codecasts/ambientum#67]
Quando utilizo uma porta diferente da padrão do Mysql o container "app" não se comunica com o container "mysql', mesmo tudo está corretamente configurado. Segue os arquivos:

docker-compose.yml
```
# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  base-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: base-mysql
    volumes:
      - base-mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=base
      - MYSQL_DATABASE=base
      - MYSQL_USER=base
      - MYSQL_PASSWORD=base

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-nginx
    container_name: base-app
    volumes:
      - .:/var/www/app
    ports:
      - "801:8080"
    links:
      - mysql
```

.env
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:4XKpsnLwdcJAYpwTceew6xssdKcf6S/YcRDCXaUwA5Y=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=33061
DB_DATABASE=base
DB_USERNAME=base
DB_PASSWORD=base

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
```
Com essa mesma configuração, se eu altero para a porta padrão do Mysql volta a funcionar.
