### ISSUE TITLE
Laravel with YARN and BROWSERSYNC

### ISSUE THREAD

**Issue by loooping** [codecasts/ambientum#88]
Bellow my docker-compose.yml for Laravel 5.5 (FRESH INSTALL)

- YARN extremely slow and BrowserSync not work

My question is How to put all together the right way?

```
# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  apptest-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: apptest-mysql
    volumes:
      - apptest-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lo_apptest
      - MYSQL_USER=apptest
      - MYSQL_PASSWORD=webmaster

  # Web server - For live reload and development
  # This environment can be used to run npm and node
  # commands as well
  dev:
    image: ambientum/node:lts
    container_name: apptest-app-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: apptest-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
```

Extremely slow to build `dev` assets
Steps to reproduce: `docker-compose run dev yarn dev`
Output #1 Execution

```
yarn run v1.3.2
$ npm run development

> @ development /var/www/app
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Additional dependencies must be installed. This will only take a moment.
warning " > browser-sync-webpack-plugin@2.0.1" has unmet peer dependency "webpack@^1 || ^2 || ^3".
Finished. Please run Mix again.
Done in 315.66s.
```

Output #2  Execution

```
 DONE  Compiled successfully in 24164ms                                                                                                                                  20:15:29

       Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.37 MB       0  [emitted]  [big]  /js/app
/css/app.css   187 kB       0  [emitted]         /js/app
Done in 65.56s.
```

And `docker-compose run dev yarn watch`

Output

```
DONE  Compiled successfully in 17431ms                                                                                                                                    20:24:16

       Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.37 MB       0  [emitted]  [big]  /js/app
/css/app.css   187 kB       0  [emitted]         /js/app
[Browsersync] Proxying: http://apptest.ooo
[Browsersync] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://172.26.0.5:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://172.26.0.5:3001
 -----------------------------------
[Browsersync] Watching files...
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```

**Comment by hernandev** [comment]
@loooping Considering the given `docker-compose.yml` file

```
dev:
    image: ambientum/node:lts
    container_name: apptest-app-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080
```

this actually re-download everything on each execution, since there are no persistent caching volumes.

How to fix it:

Declare 4, yes, 4 new volumes:
```
volumes:
  # ~/.config
  dot-config:
  # ~/.local
  dot-local:
  # ~/.cache
  dot-cache:
  # ~/.composer (php only)
  dot-composer:
```

Then on the NPM and PHP containers, mount like this:

```
dev:
    image: ambientum/node:lts
    container_name: apptest-app-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    ports:
      - 8080:8080
```

This way, things will run faster, since there are caching. and now, you can even install global stuff, like:

```
docker-compose run dev yarn global add vue-cli
docker-compose run dev vue --version
```

**Comment by loooping** [comment]
Run `docker-compose run dev yarn global add vue-cli` output is

```
yarn global v1.3.2
warning Skipping preferred cache folder "/home/ambientum/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/ambientum/.config/yarn'".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
Run `docker-compose run dev vue --version` output is

```
[FATAL tini (6)] exec vue failed: No such file or directory
```

My docker-compose.yml NOW

```
# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  apptest-mysql-data:
    driver: local
  # ~/.config
  dot-config:
  # ~/.local
  dot-local:
  # ~/.cache
  dot-cache:
  # ~/.composer (php only)
  dot-composer:

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: apptest-mysql
    volumes:
      - apptest-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lo_apptest
      - MYSQL_USER=apptest
      - MYSQL_PASSWORD=webmaster

  # Web server - For live reload and development
  # This environment can be used to run npm and node
  # commands as well
  dev:
    image: ambientum/node:lts
    container_name: apptest-app-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    ports:
      - 8080:8080

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: apptest-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
```

And I try run `docker-compose run dev yarn watch` **Doesn't Works** output:

```
yarn run v1.3.2
warning Skipping preferred cache folder "/home/ambientum/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
 10% building modules 1/1 modules 0 active
Webpack is watching the files…

 95% emitting

 ERROR  Failed to compile with 2 errors                                                                                                                                    15:31:54

 error  in ./resources/assets/sass/app.scss

Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/var/www/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)

 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/var/www/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/var/www/app/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/var/www/app/node_modules/webpack/lib/Compilation.js:454:10)
    at runLoaders (/var/www/app/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/var/www/app/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/var/www/app/node_modules/webpack/lib/Compilation.js:454:10)
    at factory (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /var/www/app/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/var/www/app/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/var/www/app/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:196:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

     Asset     Size  Chunks                    Chunk Names
/js/app.js  1.37 MB       0  [emitted]  [big]  /js/app

ERROR in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/lib/loader.js??ref--6-5!./resources/assets/sass/app.scss
Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/var/www/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /var/www/app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/var/www/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/var/www/app/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/var/www/app/node_modules/webpack/lib/Compilation.js:454:10)
    at runLoaders (/var/www/app/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/app/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/var/www/app/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/var/www/app/node_modules/webpack/lib/Compilation.js:454:10)
    at factory (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /var/www/app/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/var/www/app/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/var/www/app/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/var/www/app/node_modules/webpack/lib/NormalModuleFactory.js:196:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
[Browsersync] Proxying: http://apptest.ooo
[Browsersync] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://172.26.0.3:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://172.26.0.3:3001
 -----------------------------------
[Browsersync] Watching files...
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```
