### ISSUE TITLE
PHP Extension php7-mailparse

### ISSUE THREAD

**Issue by eduardokum** [codecasts/ambientum#96]
Is there any change you add to the extension 'php7-mailparse'?

I tried `sudo apk add php7-mailparse` 

but I get the error
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mailparse' (tried: /usr/lib/php7/modules/mailparse (Error loading shared library /usr/lib/php7/modules/mailparse: No such file or directory), /usr/lib/php7/modules/mailparse.so (Error relocating /usr/lib/php7/modules/mailparse.so: spprintf: symbol not found)) in Unknown on line 0
```

**Comment by hernandev** [comment]
Did not knew about this extension, is it a PECL extension? If yes, and there are no musl problems to compile, sure.

**Comment by eduardokum** [comment]
Hello, I try
```
sudo pecl install --nodeps mailparse
```

but I get
```
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
warning: pecl/mailparse requires PHP extension "mbstring"
downloading mailparse-3.0.2.tar ...
Starting to download mailparse-3.0.2.tar (195,584 bytes)
.........................................done: 195,584 bytes
10 source files, building
running: phpize7
sh: phpize7: not found
ERROR: `phpize' failed
```

If I try install php7-dev all extensions get crazy 

```
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/mysqli' - Error loading shared library /usr/lib/php7/modules/mysqli: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/openssl' - Error loading shared library /usr/lib/php7/modules/openssl: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pcntl' - Error loading shared library /usr/lib/php7/modules/pcntl: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdo' - Error loading shared library /usr/lib/php7/modules/pdo: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdo_pgsql' - Error loading shared library /usr/lib/php7/modules/pdo_pgsql: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pgsql' - Error loading shared library /usr/lib/php7/modules/pgsql: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/posix' - Error loading shared library /usr/lib/php7/modules/posix: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/session' - Error loading shared library /usr/lib/php7/modules/session: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/sodium' - Error loading shared library /usr/lib/php7/modules/sodium: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/sqlite3' - Error loading shared library /usr/lib/php7/modules/sqlite3: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/xml' - Error loading shared library /usr/lib/php7/modules/xml: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/zip' - Error loading shared library /usr/lib/php7/modules/zip: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/zlib' - Error loading shared library /usr/lib/php7/modules/zlib: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/dom' - Error loading shared library /usr/lib/php7/modules/dom: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/mysqlnd' - Error loading shared library /usr/lib/php7/modules/mysqlnd: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/phar' - Error loading shared library /usr/lib/php7/modules/phar: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/soap' - Error loading shared library /usr/lib/php7/modules/soap: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/xmlreader' - Error loading shared library /usr/lib/php7/modules/xmlreader: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdo_mysql' - Error loading shared library /usr/lib/php7/modules/pdo_mysql: No such file or directory in Unknown on line 0
pdv-queue | PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/redis' - Error loading shared library /usr/lib/php7/modules/redis: No such file or directory in Unknown on line 0
```

**Comment by hernandev** [comment]
@eduardokum All of those problems were solved on the last release.

BUT, i've included the php-mailparse extension on the php-alpine repository, you can now install it by doing:

```
apk add --update php-mailparse@php
```

Notice that all extensions and packages now can be used without the `7`, but the `7` can be still used:

```
apk add --update php7-mailparse@php
``` 

Should also work.

I've built `mailparse` for the 4 variants, Alpine v3.6 and v3.7 in both PHP 7.1 and PHP 7.2

Thanks!

**Comment by hernandev** [comment]
which version of alpine and php?

**Comment by eduardokum** [comment]
```yaml
# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  pdv-mysql-data:
    driver: local

  # Redis Data
  pdv-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: pdv-mysql
    volumes:
      - pdv-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pdv
      - MYSQL_DATABASE=pdv
      - MYSQL_USER=pdv
      - MYSQL_PASSWORD=pdv

  # Redis
  cache:
    image: redis:4.0
    container_name: pdv-redis
    command: --appendonly yes
    volumes:
      - pdv-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:latest-nginx
    container_name: pdv-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    environment:
      - XDEBUG_ENABLED=true
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: pdv-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
```
